name: Harsh Sheth
favicon: null
layout_spectrum: 0.9800151546951383
typography_spectrum: 0.6515131511259824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8960553463548422
  lightness: 0.8141563867684454
  saturation: 0.33404536196030676
  rhythmicContrast: 0.7876211970578879
purpose: []
